In [1]:
import numpy as np

In [5]:
a = np.array([1,3,4])

In [6]:
print(a)

[1 3 4]


#mas de una dimension

In [9]:
b = np.array([[1,2],[2,3]])

In [10]:
print(b)

[[1 2]
 [2 3]]


minima dimension

In [19]:
c=np.array([1,3,4,5,6,7,8], ndmin=2)

In [20]:
print(c)

[[1 3 4 5 6 7 8]]
